[theme]
primaryColor = "#00cc66"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1e293b"
textColor = "#fafafa"
font = "sans serif"

[server]
headless = true
enableCORS = false
port = 8501

[browser]
gatherUsageStats = false
